repos:
  # Basic file checks - All auto-fix enabled
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md] # Auto-fixes trailing whitespace
      - id: end-of-file-fixer # Auto-fixes missing newline at end of file
      - id: mixed-line-ending
        args: [--fix=lf] # Auto-fixes to use LF line endings
      - id: fix-byte-order-marker # Auto-removes UTF-8 BOM

  # Shell script formatting with shfmt - Already auto-fixes
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-1
    hooks:
      - id: shfmt
        args: [-w, -s, -i, '4'] # Write (auto-fix), simplify, indent 4 spaces
        files: ^scripts/.*\.sh$

  # YAML formatting with prettier - Auto-fixes YAML syntax and formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: Auto-format YAML files
        types: [yaml]
        files: \.(yml|yaml)$
        args: [--write, --single-quote] # Auto-fixes and uses single quotes

  # YAML validation (runs after prettier fixes)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        name: Validate YAML syntax
        exclude: ^extracted/

  # Note: shellcheck removed as it only reports issues, doesn't fix them
  # Run manually with: make lint
