repos:
  # Basic file checks - All auto-fix enabled
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]  # Auto-fixes trailing whitespace
      - id: end-of-file-fixer  # Auto-fixes missing newline at end of file
      - id: mixed-line-ending
        args: [--fix=lf]  # Auto-fixes to use LF line endings
      - id: fix-byte-order-marker  # Auto-removes UTF-8 BOM

  # Shell script formatting with shfmt - Already auto-fixes
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-1
    hooks:
      - id: shfmt
        args: [-w, -s, -i, '4']  # Write (auto-fix), simplify, indent 4 spaces
        files: ^scripts/.*\.sh$

  # Note: shellcheck and check-yaml removed as they only report issues, don't fix them
  # Run these manually with: make lint
